development: &defaults
  :facebook:
    :app_id: 111
    :secret_key: 222
    :scope: "email,user_birthday,read_stream"
    :display: "popup"
    :image_size: "large"

  :vkontakte:
    :app_id: 111
    :app_secret: 222
    :scope: "notify,wall,offline"

production:
  <<: *defaults