development: &defaults
  :facebook:
    :app_id: 111
    :app_secret: 222
    :scope: "email,user_birthday,read_stream"
    :display: "popup"
    :image_size: "large"

  :vkontakte:
    :app_id: 111
    :app_secret: 222
    :scope: "notify,offline"
    :display: "popup"

  :twitter:
    :app_key: 111
    :app_secret: 222

production:
  <<: *defaults